sudo: false
language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy

cache:
  apt: true
  pip: true
  directories:
      - $HOME/download-cache

addons:
  apt_packages:
    - default-jdk

install:
    - pip install 'requests>2' coveralls
    - pip install .

before_script:
    - BACKGROUND_SOLR=true tests/start-solr-test-server.sh

script:
    - python tests/wait-for-solr.py
    - python setup.py nosetests

after_success:
    - coveralls

notifications:
    email: false
